package com.pojo;

// Generated 20 Jul, 2019 2:58:07 PM by Hibernate Tools 3.4.0.CR1

/**
 * Fees generated by hbm2java
 */
public class Fees implements java.io.Serializable {

	private Integer feeid;
	private Admission admission;
	private String fname;
	private String lname;
	private int totalfees;
	private int finst;
	private String fdate;
	private int sinst;
	private String sdate;
	private int tinst;
	private String tdate;
	private int rbalance;

	public Fees() {
	}

	public Fees(String fname, String lname, int totalfees, int finst, String fdate, int sinst, String sdate, int tinst,
			String tdate, int rbalance) {
		this.fname = fname;
		this.lname = lname;
		this.totalfees = totalfees;
		this.finst = finst;
		this.fdate = fdate;
		this.sinst = sinst;
		this.sdate = sdate;
		this.tinst = tinst;
		this.tdate = tdate;
		this.rbalance = rbalance;
	}

	public Fees(Admission admission, String fname, String lname, int totalfees, int finst, String fdate, int sinst,
			String sdate, int tinst, String tdate, int rbalance) {
		this.admission = admission;
		this.fname = fname;
		this.lname = lname;
		this.totalfees = totalfees;
		this.finst = finst;
		this.fdate = fdate;
		this.sinst = sinst;
		this.sdate = sdate;
		this.tinst = tinst;
		this.tdate = tdate;
		this.rbalance = rbalance;
	}

	public Integer getFeeid() {
		return this.feeid;
	}

	public void setFeeid(Integer feeid) {
		this.feeid = feeid;
	}

	public Admission getAdmission() {
		return this.admission;
	}

	public void setAdmission(Admission admission) {
		this.admission = admission;
	}

	public String getFname() {
		return this.fname;
	}

	public void setFname(String fname) {
		this.fname = fname;
	}

	public String getLname() {
		return this.lname;
	}

	public void setLname(String lname) {
		this.lname = lname;
	}

	public int getTotalfees() {
		return this.totalfees;
	}

	public void setTotalfees(int totalfees) {
		this.totalfees = totalfees;
	}

	public int getFinst() {
		return this.finst;
	}

	public void setFinst(int finst) {
		this.finst = finst;
	}

	public String getFdate() {
		return this.fdate;
	}

	public void setFdate(String fdate) {
		this.fdate = fdate;
	}

	public int getSinst() {
		return this.sinst;
	}

	public void setSinst(int sinst) {
		this.sinst = sinst;
	}

	public String getSdate() {
		return this.sdate;
	}

	public void setSdate(String sdate) {
		this.sdate = sdate;
	}

	public int getTinst() {
		return this.tinst;
	}

	public void setTinst(int tinst) {
		this.tinst = tinst;
	}

	public String getTdate() {
		return this.tdate;
	}

	public void setTdate(String tdate) {
		this.tdate = tdate;
	}

	public int getRbalance() {
		return this.rbalance;
	}

	public void setRbalance(int rbalance) {
		this.rbalance = rbalance;
	}

}
