package com.pojo;

// Generated 20 Jul, 2019 2:58:07 PM by Hibernate Tools 3.4.0.CR1

/**
 * Grade generated by hbm2java
 */
public class Grade implements java.io.Serializable {

	private Integer gid;
	private String name;
	private String course;
	private Integer tmarks;
	private Integer omarks;
	private String status;

	public Grade() {
	}

	public Grade(String name, String course, Integer tmarks, Integer omarks, String status) {
		this.name = name;
		this.course = course;
		this.tmarks = tmarks;
		this.omarks = omarks;
		this.status = status;
	}

	public Integer getGid() {
		return this.gid;
	}

	public void setGid(Integer gid) {
		this.gid = gid;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getCourse() {
		return this.course;
	}

	public void setCourse(String course) {
		this.course = course;
	}

	public Integer getTmarks() {
		return this.tmarks;
	}

	public void setTmarks(Integer tmarks) {
		this.tmarks = tmarks;
	}

	public Integer getOmarks() {
		return this.omarks;
	}

	public void setOmarks(Integer omarks) {
		this.omarks = omarks;
	}

	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

}
