package com.pojo;

// Generated 20 Jul, 2019 2:58:07 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * Message generated by hbm2java
 */
public class Message implements java.io.Serializable {

	private Integer mid;
	private String name;
	private String email;
	private String msg;
	private Date msgdate;

	public Message() {
	}

	public Message(String name, String email, String msg, Date msgdate) {
		this.name = name;
		this.email = email;
		this.msg = msg;
		this.msgdate = msgdate;
	}

	public Integer getMid() {
		return this.mid;
	}

	public void setMid(Integer mid) {
		this.mid = mid;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public String getMsg() {
		return this.msg;
	}

	public void setMsg(String msg) {
		this.msg = msg;
	}

	public Date getMsgdate() {
		return this.msgdate;
	}

	public void setMsgdate(Date msgdate) {
		this.msgdate = msgdate;
	}

}
