package com.pojo;

// Generated 20 Jul, 2019 2:58:07 PM by Hibernate Tools 3.4.0.CR1

/**
 * Placement generated by hbm2java
 */
public class Placement implements java.io.Serializable {

	private Integer pid;
	private String name;
	private String company;
	private String profile;
	private String package_;

	public Placement() {
	}

	public Placement(String name, String company, String profile, String package_) {
		this.name = name;
		this.company = company;
		this.profile = profile;
		this.package_ = package_;
	}

	public Integer getPid() {
		return this.pid;
	}

	public void setPid(Integer pid) {
		this.pid = pid;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getCompany() {
		return this.company;
	}

	public void setCompany(String company) {
		this.company = company;
	}

	public String getProfile() {
		return this.profile;
	}

	public void setProfile(String profile) {
		this.profile = profile;
	}

	public String getPackage_() {
		return this.package_;
	}

	public void setPackage_(String package_) {
		this.package_ = package_;
	}

}
