package com.pojo;

// Generated 20 Jul, 2019 2:58:07 PM by Hibernate Tools 3.4.0.CR1

/**
 * Register generated by hbm2java
 */
public class Register implements java.io.Serializable {

	private Integer regid;
	private String fname;
	private String lname;
	private String username;
	private String password;
	private String email;
	private String contact;

	public Register() {
	}

	public Register(String fname, String lname, String username, String password, String email, String contact) {
		this.fname = fname;
		this.lname = lname;
		this.username = username;
		this.password = password;
		this.email = email;
		this.contact = contact;
	}

	public Integer getRegid() {
		return this.regid;
	}

	public void setRegid(Integer regid) {
		this.regid = regid;
	}

	public String getFname() {
		return this.fname;
	}

	public void setFname(String fname) {
		this.fname = fname;
	}

	public String getLname() {
		return this.lname;
	}

	public void setLname(String lname) {
		this.lname = lname;
	}

	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public String getContact() {
		return this.contact;
	}

	public void setContact(String contact) {
		this.contact = contact;
	}

}
